server:
  port: '8082'
  
eureka:
  instance:
    hostname: localhost
  
jwt:
  secret: secret
spring:
  data:
    mongodb:
      database: cplayer2
      port: 27017
      uri: mongodb://localhost:27017/cplayer2
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: USER-SERVICE
useSSL: false
data:
  exception:
    message1: User Cannot Register because already exists.